name: Demo Python Workflow
on: [push]
jobs:
  run-app:
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python main.py
